# Generated by Django 6.0.3 on 2026-03-31 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
    ]
